# NumPy Basics
NumPy (Numerical Python) provides fast, memory-efficient array operations. The foundation of scientific computing and ML in Python.

## 1. Creating Arrays

In [1]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.array([[1, 2, 3], [4, 5, 6]])

print(a)
print(b)
print("Shape of b:", b.shape)
print("Dimensions of b:", b.ndim)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
Shape of b: (2, 3)
Dimensions of b: 2


In [2]:
# Common array creation shortcuts
print(np.zeros((2, 3)))
print(np.ones((2, 3)))
print(np.arange(0, 10, 2))       # start, stop, step
print(np.linspace(0, 1, 5))      # 5 evenly spaced values between 0 and 1
print(np.eye(3))                  # identity matrix

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 2. Indexing and Slicing

In [3]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])
print(arr[1:4])
print(arr[::-1])   # reversed

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix[1, 2])     # row 1, col 2
print(matrix[:, 0])      # all rows, first column
print(matrix[0:2, 0:2])  # sub-matrix

10
[20 30 40]
[50 40 30 20 10]
6
[1 4 7]
[[1 2]
 [4 5]]


## 3. Array Operations (Vectorized)

In [4]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])

print(x + y)
print(x * y)
print(x ** 2)
print(y / x)
print(np.sqrt(y))

[11 22 33]
[10 40 90]
[1 4 9]
[10. 10. 10.]
[3.16227766 4.47213595 5.47722558]


## 4. Broadcasting
NumPy automatically expands smaller arrays to match shapes during operations.

In [5]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
vector = np.array([10, 20, 30])

print(matrix + vector)   # vector is 'broadcast' across each row

[[11 22 33]
 [14 25 36]]


## 5. Reshaping

In [6]:
arr = np.arange(12)
print(arr)

reshaped = arr.reshape(3, 4)
print(reshaped)

print(reshaped.flatten())  # back to 1D

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


## 6. Aggregate Functions

In [7]:
data = np.array([[1, 2, 3], [4, 5, 6]])

print("Sum:", data.sum())
print("Column-wise sum:", data.sum(axis=0))
print("Row-wise sum:", data.sum(axis=1))
print("Mean:", data.mean())
print("Max:", data.max())
print("Std Dev:", data.std())

Sum: 21
Column-wise sum: [5 7 9]
Row-wise sum: [ 6 15]
Mean: 3.5
Max: 6
Std Dev: 1.707825127659933


## Summary
NumPy arrays are faster and more memory-efficient than Python lists because they store homogeneous data and support vectorized operations, avoiding slow Python-level loops.